# Generated by Django 2.2.6 on 2019-10-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senka',
            fields=[
                ('senkaId', models.IntegerField(primary_key=True, serialize=False)),
                ('maxBoxNum', models.IntegerField()),
                ('minBoxNum', models.IntegerField()),
                ('senkaNum', models.IntegerField()),
            ],
        ),
    ]
