# Generated by Django 2.2.6 on 2019-10-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenkaCalc', '0002_auto_20191015_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senka',
            name='maxBoxNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
